#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x58D0EE648A48B3BB (faure@kde.org)
#
Name     : ktextwidgets
Version  : 5.48.0
Release  : 1
URL      : https://download.kde.org/stable/frameworks/5.48/ktextwidgets-5.48.0.tar.xz
Source0  : https://download.kde.org/stable/frameworks/5.48/ktextwidgets-5.48.0.tar.xz
Source99 : https://download.kde.org/stable/frameworks/5.48/ktextwidgets-5.48.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.0 LGPL-2.1
Requires: ktextwidgets-lib
Requires: ktextwidgets-license
Requires: ktextwidgets-data
Requires: ktextwidgets-locales
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : kcodecs-dev
BuildRequires : kcompletion-dev
BuildRequires : ki18n-dev
BuildRequires : kiconthemes-dev
BuildRequires : kservice-dev
BuildRequires : kwidgetsaddons-dev
BuildRequires : kwindowsystem-dev
BuildRequires : sonnet-dev

%description
# KTextWidgets
Text editing widgets
## Introduction
KTextWidgets provides widgets for displaying and editing text. It supports
rich text as well as plain text.

%package data
Summary: data components for the ktextwidgets package.
Group: Data

%description data
data components for the ktextwidgets package.


%package dev
Summary: dev components for the ktextwidgets package.
Group: Development
Requires: ktextwidgets-lib
Requires: ktextwidgets-data
Provides: ktextwidgets-devel

%description dev
dev components for the ktextwidgets package.


%package lib
Summary: lib components for the ktextwidgets package.
Group: Libraries
Requires: ktextwidgets-data
Requires: ktextwidgets-license

%description lib
lib components for the ktextwidgets package.


%package license
Summary: license components for the ktextwidgets package.
Group: Default

%description license
license components for the ktextwidgets package.


%package locales
Summary: locales components for the ktextwidgets package.
Group: Default

%description locales
locales components for the ktextwidgets package.


%prep
%setup -q -n ktextwidgets-5.48.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532027375
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1532027375
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/ktextwidgets
cp COPYING.LIB %{buildroot}/usr/share/doc/ktextwidgets/COPYING.LIB
cp COPYING.LGPL-2 %{buildroot}/usr/share/doc/ktextwidgets/COPYING.LGPL-2
pushd clr-build
%make_install
popd
%find_lang ktextwidgets5

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/kservicetypes5/kregexpeditor.desktop

%files dev
%defattr(-,root,root,-)
/usr/include/KF5/KTextWidgets/KFind
/usr/include/KF5/KTextWidgets/KFindDialog
/usr/include/KF5/KTextWidgets/KPluralHandlingSpinBox
/usr/include/KF5/KTextWidgets/KRegExpEditorInterface
/usr/include/KF5/KTextWidgets/KReplace
/usr/include/KF5/KTextWidgets/KReplaceDialog
/usr/include/KF5/KTextWidgets/KRichTextEdit
/usr/include/KF5/KTextWidgets/KRichTextWidget
/usr/include/KF5/KTextWidgets/KTextEdit
/usr/include/KF5/KTextWidgets/kfind.h
/usr/include/KF5/KTextWidgets/kfinddialog.h
/usr/include/KF5/KTextWidgets/kpluralhandlingspinbox.h
/usr/include/KF5/KTextWidgets/kregexpeditorinterface.h
/usr/include/KF5/KTextWidgets/kreplace.h
/usr/include/KF5/KTextWidgets/kreplacedialog.h
/usr/include/KF5/KTextWidgets/krichtextedit.h
/usr/include/KF5/KTextWidgets/krichtextwidget.h
/usr/include/KF5/KTextWidgets/ktextedit.h
/usr/include/KF5/KTextWidgets/ktextwidgets_export.h
/usr/include/KF5/ktextwidgets_version.h
/usr/lib64/cmake/KF5TextWidgets/KF5TextWidgetsConfig.cmake
/usr/lib64/cmake/KF5TextWidgets/KF5TextWidgetsConfigVersion.cmake
/usr/lib64/cmake/KF5TextWidgets/KF5TextWidgetsTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KF5TextWidgets/KF5TextWidgetsTargets.cmake
/usr/lib64/libKF5TextWidgets.so
/usr/lib64/qt5/mkspecs/modules/qt_KTextWidgets.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libKF5TextWidgets.so.5
/usr/lib64/libKF5TextWidgets.so.5.48.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/ktextwidgets/COPYING.LGPL-2
/usr/share/doc/ktextwidgets/COPYING.LIB

%files locales -f ktextwidgets5.lang
%defattr(-,root,root,-)

